### ISSUE TITLE
@import "vars" required in individual file to work

### ISSUE THREAD

**Issue by nklansford** [nklansford/keyway#11]
I have all of my `@import "[insert-partial-name-here]"` links in my styles.scss file. I also have a mixins file setup as well as a vars. In my vars file, I have a line that says `$font-body: 'Heebo', sans-serif;` and in my type file I have
```
body{
  @include type-setup($font-body, 1.4rem, 400);
  width: $width-mobile;
}
```
I get a console error saying that `$font-body` is not defined. However, when I put `@import "vars";` in my type file it goes away and works. I thought that I only needed to import files in the `styles.scss` file. Also, I don't have mixins imported there and that seems to work just fine. Anything I am missing?

**Comment by philschanely** [comment]
Glad you noticed this as its a gap in my instructions. 

You'll simply need to ensure that `vars` and `mixins` are the first two sass sheets you import in `styles.scss`. This way they're available from then on as you continue to import the other files and use/call those variables and mixins thereafter.

- [x] Adjust order of imports so that vars and mixins are at the top of the document, followed by other files.

**Comment by nklansford** [comment]
Thanks!
