### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by nklansford** [nklansford/keyway#2]
reformat current css to sass

**Comment by philschanely** [comment]
Yes: 

- [x] Reformat into the folder structure shown in the simple starter
- [x] Add the package.json scripts so that you can develop locally, including the Sass portion
- [x] Use Sass variables
- [x] Use Sass partials and imports to break up the styles into separate files imported into the central `styles.scss` file
- [x] Use nesting to simplify selectors
- [x] Add at least one mixin to replace common sets of properties

**Comment by nklansford** [comment]
Have it setup and implemented. Will continue to use them for layouts.
